# Setup
title:               My Notes
description:         "Aratrik Pal's Notes"
#url:                 https://ap2008.github.io/
baseurl:             '/Notes'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Aratrik Pal
  url:               https://thunder2020.pythonanywhere.com
  email:             aratrik.pal@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-pandoc

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
markdown: Pandoc
algolia:
  application_id: 'IBCSC9FLK2'
  index_name: jekyll
  vars: ["title", "excerpt", "date", "url", "categories", "tags"]
exclude: [vendor]
